### ISSUE TITLE
Can't Load in Static js and css using react.js config

### ISSUE THREAD

**Issue by dagogodboss** [brunocangs/adonis-react-view-provider#1]
`module.exports = {
    toStatic: false, 
    useCustomWrapper: false, 
    wrapperFile: 'main', 
    title: 'Adonis React App',
    template: `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
        <title>{{title}}</title>
        
        <link rel="stylesheet" type="text/css" href="/public/css/font-awesome.min.css">

        
        
        <link rel="stylesheet" type="text/css" href="/public/css/animate.css">
        <link rel="stylesheet" type="text/css" href="/public/css/cryptocoins.css">
        <link rel="stylesheet" type="text/css" href="/plugins/c3-chart/c3.css">

        
        <link rel="stylesheet" type="text/css" href="/public/css/global.style.css">

        
        <link rel="stylesheet" href="/public/css/swiper.min.css">
        <link rel="stylesheet" href="/public/css/jqcandlestick.css">

        
        <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/public/plugins/turbo-slider/turbo.css">
    </head>
    <body>
        <div id="root">{{content}}</div>
        <script>
            window.props = {{stringifiedProps}}
        </script>
        <script src=/public/vendor.js></script>
        <script src=/public/{{viewName}}.js></script>
        <script src=/public/render.js></script>
        <script>
            window.render('{{viewName}}');
        </script>
        <script src="/public/js/jquery-3.2.1.min.js"></script>

        
        <script src="/public/js/swiper.min.js"></script>

        
        
        
        <script src="/public/plugins/c3-chart/c3.min.js"></script>
        <script src="/public/plugins/c3-chart/d3.min.js"></script>
        <script src="/public/plugins/c3-chart/c3.custom.js"></script>
        
        <script src="/public/plugins/flot/jquery.flot.min.js"></script>
        <script src="/public/plugins/flot/jquery.flot.time.min.js"></script>
        <script src="/public/plugins/flot/jquery.flot.pie.min.js"></script>
        <script src="/public/plugins/flot/jquery.flot.tooltip.min.js"></script>
        <script src="/public/plugins/flot/jquery.flot.resize.min.js"></script>
        
        <script src="/public/plugins/jquery-sparkline/jquery.sparkline.js"></script>

        <script src="/public/js/jquery.jqcandlestick.min.js"></script>
        <script src="/public/js/candle-stick-ini.js"></script>

        jquery.jqcandlestick.min

        
        <script src="/public/js/app-charts.js"></script>
        <script src="/public/js/global.script.js"></script>
    </body>
    </html>`
}`

It returns 404 error

**Comment by brunocangs** [comment]
Hi, sorry for seeing this after such a long time. I don't actively maintain this repo and would suggest you check you this other package instead
https://github.com/zakodium/adonis-react
